In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
# Copiando o caminho do arquivo onde estão as tables bronze:
caminho_raw = r"C:\Users\caldo\OneDrive\Desktop\Projetos_GIT\project_01_brazilian_ecommerce\data\1_bronze"

# Aqui faço uma simples correção das barras, troco a barra '\' pela '/':
caminho = caminho_raw.replace('\\','/') + '/'
print('Caminho base para os arquivos:')
print(caminho)
print()

# Aqui eu listo os arquivos CSV que estão presentes dentro da pasta 'raw':
lista = os.listdir(caminho)
print(lista)

# Configurando o caminho de direcionamento para salvar os arquivos no diretório silver:
caminho_silver_raw = r'C:\Users\caldo\OneDrive\Desktop\Projetos_GIT\project_01_brazilian_ecommerce\data\2_silver'
caminho_silver = caminho_silver_raw.replace('\\','/') + '/'
caminho_silver

Caminho base para os arquivos:
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/

['olist_customers_dataset.csv', 'olist_geolocation_dataset.csv', 'olist_orders_dataset.csv', 'olist_order_items_dataset.csv', 'olist_order_payments_dataset.csv', 'olist_order_reviews_dataset.csv', 'olist_products_dataset.csv', 'olist_sellers_dataset.csv', 'product_category_name_translation.csv']

'C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/2_silver/'

In [3]:
# Faço o mesmo processo para criar o caminho completo dos arquivos no repositório:
caminhos = []
for arquivo in lista:
    caminho_completo = caminho + arquivo
    caminhos.append(caminho_completo)

for arquivo in caminhos:
    print(arquivo)

C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_customers_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_geolocation_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_orders_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_order_items_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_order_payments_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_order_reviews_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_products_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/olist_sellers_dataset.csv
C:/Users/caldo/OneDrive/Desktop/Projetos_GIT/project_01_brazilian_ecommerce/data/1_bronze/product_category_name_translation.csv

In [4]:
# Criação dos DataFrames com os caminhos dos arquivos:
df_customer = pd.read_csv(caminhos[0])
df_geolocalizacao = pd.read_csv(caminhos[1])
df_pedidos = pd.read_csv(caminhos[2])
df_itens_pedidos = pd.read_csv(caminhos[3])
df_ordem_pagamento = pd.read_csv(caminhos[4])
df_revisao_pedidos = pd.read_csv(caminhos[5])
df_produtos = pd.read_csv(caminhos[6])
df_vendedores = pd.read_csv(caminhos[7])
df_categoria_translacao = pd.read_csv(caminhos[8])

## DF_CUSTOMER

In [5]:
# Conferência do topo da tabela, verificar se as colunas vieram na linha correta:
df_customer.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,data_ingestao
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,2026-04-06 20:41:47.381954
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,2026-04-06 20:41:47.381954
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,2026-04-06 20:41:47.381954
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,2026-04-06 20:41:47.381954
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,2026-04-06 20:41:47.381954

In [6]:
# Conferência da base da tabela, é bom para ver se não tem uma linha de soma da coluna por exemplo:
df_customer.tail()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,data_ingestao
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP,2026-04-06 20:41:47.381954
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP,2026-04-06 20:41:47.381954
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE,2026-04-06 20:41:47.381954
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS,2026-04-06 20:41:47.381954
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP,2026-04-06 20:41:47.381954

In [7]:
# Com o '.info()' eu consigo ter uma visão geral de como está a estruturação da tabela, 
# quantidade de colunas e linhas, valores nulos e tipagem dos dados:
df_customer.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  object
 4   customer_state            99441 non-null  object
 5   data_ingestao             99441 non-null  object
dtypes: int64(1), object(5)
memory usage: 4.6+ MB

In [8]:
# Definição de schema do df_customer:
schema_df_customer = {
    'customer_id' : 'string', 
    'customer_unique_id' : 'string', 
    'customer_zip_code_prefix' : 'string',
    'customer_city' : 'string', 
    'customer_state' : 'string', 
    'data_ingestao' : 'datetime64[ns]'
}


# Código para reatribuir uma tipagem de dados correta no DataFrame:
    # OBS: no caso do ajuste da data, precisamos atribuir uma regra diferente
    # o coerse é para corrigir caso tenha algum dado de data errado no dataframe
for coluna, tipo_esperado in schema_df_customer.items():
    if "datetime" in tipo_esperado:
        df_customer[coluna] = pd.to_datetime(df_customer[coluna], errors="coerce")
    else:
        df_customer[coluna] = df_customer[coluna].astype(tipo_esperado)

In [9]:
# Não temos nenhumo LINHA no DataFrame que se repete:
print(f'Total de linhas duplicadas:', df_customer.duplicated().sum())
# Mas nós precisamos analisar se temos algum ID de customer que está se repetindo (ele é a nossa PK):
print(f'Total de "customer_id" duplicados:', df_customer.duplicated(subset=["customer_id"]).sum())

# Ajustando não conformidades dentro da coluna 'customer_city':
    # Convertendo todos os valores da coluna para minúsculo e retirando espaços em branco:
df_customer["customer_city"] = df_customer["customer_city"].str.strip().str.lower()

    # Conferindo quantidade de valores únicos e printando os valores (como são municipios/cidades, o máximo deve ser 5600 +ou-):
print(f'Total de valores únicos:',df_customer['customer_city'].nunique())
print(f'Lista dos estados registrados: --> ', df_customer['customer_city'].unique())

Total de linhas duplicadas: 0
Total de "customer_id" duplicados: 0
Total de valores únicos: 4119
Lista dos estados registrados: -->  <StringArray>
[               'franca', 'sao bernardo do campo',             'sao paulo',
       'mogi das cruzes',              'campinas',        'jaragua do sul',
               'timoteo',              'curitiba',        'belo horizonte',
         'montes claros',
 ...
              'balbinos',          'serra bonita',          'venda branca',
           'sanga puita',               'queiroz',                'siriji',
   'natividade da serra',          'monte bonito',            'sao rafael',
     'eugenio de castro']
Length: 4119, dtype: string

In [10]:
# Ajustando não conformidades dentro da coluna 'customer_state':
    # Convertendo todos os valores da coluna para maiúsculo e retirando espaços em branco:
df_customer["customer_state"] = df_customer["customer_state"].str.strip().str.upper()

    # Conferindo quantidade de valores únicos e printando os valores (como são estados, o máximo deve ser 27):
print(f'Total de valores únicos:',df_customer['customer_state'].nunique())
print(f'Lista dos estados registrados: --> ', df_customer['customer_state'].unique().tolist())

# Aqui estamos apenas padronizando o prefixo do CEP:
df_customer["customer_zip_code_prefix"] = df_customer["customer_zip_code_prefix"].str.zfill(5)

Total de valores únicos: 27
Lista dos estados registrados: -->  ['SP', 'SC', 'MG', 'PR', 'RJ', 'RS', 'PA', 'GO', 'ES', 'BA', 'MA', 'MS', 'CE', 'DF', 'RN', 'PE', 'MT', 'AM', 'AP', 'AL', 'RO', 'PB', 'TO', 'PI', 'AC', 'SE', 'RR']

In [11]:
# Salvando arquivo na Silver:
df_customer.to_parquet(caminho_silver + 'customers_silver_dataset.parquet', index=False)

## DF_PEDIDOS

In [12]:
# Checagem topo da lista:
df_pedidos.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,data_ingestao
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,2026-04-06 20:41:47.411945
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,2026-04-06 20:41:47.411945
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,2026-04-06 20:41:47.411945
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,2026-04-06 20:41:47.411945
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,2026-04-06 20:41:47.411945

In [13]:
# Checagem final tabela:
df_pedidos.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,data_ingestao
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00,2026-04-06 20:41:47.411945
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,2026-04-06 20:41:47.411945
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,2026-04-06 20:41:47.411945
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,2026-04-06 20:41:47.411945
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,2026-04-06 20:41:47.411945

In [14]:
# Checagem geral da tabela. Quantidade de linhas, valores nulos, tipo de dados:
df_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 9 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  object
 4   order_approved_at              99281 non-null  object
 5   order_delivered_carrier_date   97658 non-null  object
 6   order_delivered_customer_date  96476 non-null  object
 7   order_estimated_delivery_date  99441 non-null  object
 8   data_ingestao                  99441 non-null  object
dtypes: object(9)
memory usage: 6.8+ MB

In [15]:
# Definição de schema:
schema_df_pedidos = {
    'order_id' : 'string', 
    'customer_id' : 'string', 
    'order_status' : 'string', 
    'order_purchase_timestamp' : 'datetime64[ns]',
    'order_approved_at' : 'datetime64[ns]', 
    'order_delivered_carrier_date' : 'datetime64[ns]',
    'order_delivered_customer_date' : 'datetime64[ns]', 
    'order_estimated_delivery_date' : 'datetime64[ns]',
    'data_ingestao' : 'datetime64[ns]'
}

# Ajuste do tipo de dado atual com o esperado no schema:
for coluna, tipo_esperado in schema_df_pedidos.items():
    if "datetime" in tipo_esperado:
        df_pedidos[coluna] = pd.to_datetime(df_pedidos[coluna], errors="coerce")
    else:
        df_pedidos[coluna] = df_pedidos[coluna].astype(tipo_esperado)

# Conferência linhas duplicadas:
print(f'Quantidade de linhas repetidas:', df_pedidos.duplicated().sum())

# Conferência de dados duplicados na coluna 'order_id':
print(f'Quantidade de dados repetidos na coluna "order_id":', df_pedidos['order_id'].duplicated().sum())

Quantidade de linhas repetidas: 0
Quantidade de dados repetidos na coluna "order_id": 0

In [16]:
# Realizando validações da coluna order_status:
df_pedidos["order_status"] = df_pedidos["order_status"].str.strip().str.lower()

# checando quantidade de elementos presentes na coluna:
print(f'Valores únicos coluna order_status:',df_pedidos["order_status"].nunique())
print(f'Lista dos valores únicos presentes em order_status -->> ',df_pedidos["order_status"].unique().tolist())

# Contabilizando quantidade de ocorrência dos elementos:
df_pedidos["order_status"].value_counts()

Valores únicos coluna order_status: 8
Lista dos valores únicos presentes em order_status -->>  ['delivered', 'invoiced', 'shipped', 'processing', 'unavailable', 'canceled', 'created', 'approved']

order_status
delivered      96478
shipped         1107
canceled         625
unavailable      609
invoiced         314
processing       301
created            5
approved           2
Name: count, dtype: Int64

In [17]:
# Criando colunas auxiliares:
    # Criação da coluna 'data_compra':
df_pedidos['data_compra'] = df_pedidos['order_purchase_timestamp'].dt.date
df_pedidos["data_compra"] = df_pedidos["order_purchase_timestamp"].dt.normalize()

    # Criação da coluna 'tempo_de_entrega':
df_pedidos['tempo_entrega'] = (df_pedidos['order_delivered_customer_date'] - df_pedidos['order_purchase_timestamp']).dt.days

    # Criação da coluna 'atrasou_entrega', para verificar se a entrega foi entregue no prazo ou não:
df_pedidos["atrasou_entrega"] = np.where(
    df_pedidos["order_delivered_customer_date"].notna() &
    df_pedidos["order_estimated_delivery_date"].notna(),
    (df_pedidos["order_delivered_customer_date"] > df_pedidos["order_estimated_delivery_date"]).astype(int),
    np.nan
)

In [18]:
# Checando os dados de atraso na entrega:
print(df_pedidos["atrasou_entrega"].value_counts(dropna=False))
print('---'*10)

# Checando o tempo de entrega:
print(df_pedidos["tempo_entrega"].describe())

atrasou_entrega
0.0    88649
1.0     7827
NaN     2965
Name: count, dtype: int64
------------------------------
count    96476.000000
mean        12.094086
std          9.551746
min          0.000000
25%          6.000000
50%         10.000000
75%         15.000000
max        209.000000
Name: tempo_entrega, dtype: float64

In [19]:
# Quantidade de pedidos que demoraram mais que 3 meses para serem entregues:
print(df_pedidos[df_pedidos['tempo_entrega'] > 90]['tempo_entrega'].sort_values(ascending=False).nunique())

# Verificando casos onde a data de entrega é menor que a data de lançamento pedido (seria um erro):
df_pedidos[
    df_pedidos["order_delivered_customer_date"] < df_pedidos["order_purchase_timestamp"]
]

55

Empty DataFrame
Columns: [order_id, customer_id, order_status, order_purchase_timestamp, order_approved_at, order_delivered_carrier_date, order_delivered_customer_date, order_estimated_delivery_date, data_ingestao, data_compra, tempo_entrega, atrasou_entrega]
Index: []

In [20]:
# Salvando arquivo na Silver:
df_pedidos.to_parquet(caminho_silver + 'orders_silver_dataset.parquet', index=False)

## DF_ITENS_PEDIDO

In [21]:
# Conferência do topo da tabela:
df_itens_pedidos.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,data_ingestao
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,2026-04-06 20:41:47.425803
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,2026-04-06 20:41:47.425803
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,2026-04-06 20:41:47.425803
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,2026-04-06 20:41:47.425803
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,2026-04-06 20:41:47.425803

In [22]:
# Conferência da base da tabela:
df_itens_pedidos.tail()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,data_ingestao
112645,fffc94f6ce00a00581880bf54a75a037,1,4aa6014eceb682077f9dc4bffebc05b0,b8bc237ba3788b23da09c0f1f3a3288c,2018-05-02 04:11:01,299.99,43.41,2026-04-06 20:41:47.425803
112646,fffcd46ef2263f404302a634eb57f7eb,1,32e07fd915822b0765e448c4dd74c828,f3c38ab652836d21de61fb8314b69182,2018-07-20 04:31:48,350.00,36.53,2026-04-06 20:41:47.425803
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95,2026-04-06 20:41:47.425803
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72,2026-04-06 20:41:47.425803
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79,2026-04-06 20:41:47.425803

In [23]:
# Verificação de valores nulos e tipagem dos dados:
df_itens_pedidos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  object
 3   seller_id            112650 non-null  object
 4   shipping_limit_date  112650 non-null  object
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
 7   data_ingestao        112650 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 6.9+ MB

In [24]:
schema_df_itens_pedidos = {
    'order_id' : 'string', 
    'order_item_id' : 'string', 
    'product_id' : 'string', 
    'seller_id' : 'string',
    'shipping_limit_date' : 'datetime64[ns]', 
    'price' : 'float', 
    'freight_value' : 'float', 
    'data_ingestao' : 'datetime64[ns]'
}

# Ajuste do tipo de dado atual com o esperado no schema:
for coluna, tipo_esperado in schema_df_itens_pedidos.items():
    if "datetime" in tipo_esperado:
        df_itens_pedidos[coluna] = pd.to_datetime(df_itens_pedidos[coluna], errors="coerce")
    else:
        df_itens_pedidos[coluna] = df_itens_pedidos[coluna].astype(tipo_esperado)

# Conferência de linhas duplicadas:
print(f'Quantidade de linhas duplicadas:',df_itens_pedidos.duplicated().sum())

df_itens_pedidos.duplicated(subset=["order_id", "order_item_id"]).sum()

Quantidade de linhas duplicadas: 0

np.int64(0)

In [25]:
# Conferência dos dados, coluna price:
df_itens_pedidos['price'].describe()

count    112650.000000
mean        120.653739
std         183.633928
min           0.850000
25%          39.900000
50%          74.990000
75%         134.900000
max        6735.000000
Name: price, dtype: float64

In [26]:
# Conferência dos dados, coluna freight_value:
df_itens_pedidos['freight_value'].describe()

count    112650.000000
mean         19.990320
std          15.806405
min           0.000000
25%          13.080000
50%          16.260000
75%          21.150000
max         409.680000
Name: freight_value, dtype: float64

In [27]:
# Calculando custo total:
df_itens_pedidos['total_value'] = df_itens_pedidos["price"] + df_itens_pedidos["freight_value"]

In [28]:
# Salvando arquivo na Silver:
df_itens_pedidos.to_parquet(caminho_silver + 'itemns_orders_silver_dataset.parquet', index=False)

## DF_PRODUTOS

In [29]:
# Checagem topo:
df_produtos.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,data_ingestao
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,2026-04-06 20:41:47.460104
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,2026-04-06 20:41:47.460104
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,2026-04-06 20:41:47.460104
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,2026-04-06 20:41:47.460104
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,2026-04-06 20:41:47.460104

In [30]:
# Checagem final:
df_produtos.tail()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,data_ingestao
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,67.0,2.0,12300.0,40.0,40.0,40.0,2026-04-06 20:41:47.460104
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,971.0,1.0,1700.0,16.0,19.0,16.0,2026-04-06 20:41:47.460104
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,799.0,1.0,1400.0,27.0,7.0,27.0,2026-04-06 20:41:47.460104
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,156.0,2.0,700.0,31.0,13.0,20.0,2026-04-06 20:41:47.460104
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,309.0,1.0,2083.0,12.0,2.0,7.0,2026-04-06 20:41:47.460104

In [31]:
# Conferência geral do dataframe:
df_produtos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 10 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32341 non-null  object
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
 9   data_ingestao               32951 non-null  object
dtypes: float64(7), object(3)
memory usage: 2.5+ MB

In [32]:
# Schema da tabela df_produtos:
schema_df_produtos = {
    'product_id' : 'string', 
    'product_category_name' : 'string', 
    'product_name_lenght' : 'float',
    'product_description_lenght' : 'float', 
    'product_photos_qty' : 'float', 
    'product_weight_g' : 'float',
    'product_length_cm' : 'float', 
    'product_height_cm' : 'float', 
    'product_width_cm' : 'float',
    'data_ingestao' : 'datetime64[ns]'
}

# Ajustando os tipos de dados do DataFrame:
for coluna, tipo_esperado in schema_df_produtos.items():
    if "datetime" in tipo_esperado:
        df_produtos[coluna] = pd.to_datetime(df_produtos[coluna], errors="coerce")
    else:
        df_produtos[coluna] = df_produtos[coluna].astype(tipo_esperado)

In [33]:
# Checando dados duplicados na coluna product_id:
print(f'Total de duplicações coluna product_id: ',df_produtos['product_id'].duplicated().sum())

Total de duplicações coluna product_id:  0

In [34]:
# Realizando merge com a coluna de tradução:
print(df_produtos.shape)

df_produtos = df_produtos.merge(
    df_categoria_translacao,
    on="product_category_name",
    how="left"
)

df_produtos = df_produtos.rename(columns={"data_ingestao_x": "data_ingestao"})
df_produtos = df_produtos.drop(columns=["data_ingestao_y"])

(32951, 10)

In [35]:
# Validando se não houve duplicação de linha depois do merge:
df_produtos.duplicated(subset=["product_id"]).sum()

np.int64(0)

In [36]:
# Identificamos 4 valores nulos em uma coluna, mas vamos desconsiderar a relevancia:
cols_num = [
    "product_name_lenght",
    "product_description_lenght",
    "product_photos_qty",
    "product_weight_g",
    "product_length_cm",
    "product_height_cm",
    "product_width_cm"
]

for col in cols_num:
    print(col, (df_produtos[col] == 0).sum())

product_name_lenght 0
product_description_lenght 0
product_photos_qty 0
product_weight_g 4
product_length_cm 0
product_height_cm 0
product_width_cm 0

In [37]:
# Salvando arquivo na Silver:
df_produtos.to_parquet(caminho_silver + 'products_silver_dataset.parquet', index=False)

## DF_VENDEDORES

In [38]:
# Conferência do topo:
df_vendedores.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state,data_ingestao
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP,2026-04-06 20:41:47.476643
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP,2026-04-06 20:41:47.476643
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ,2026-04-06 20:41:47.476643
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP,2026-04-06 20:41:47.476643
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP,2026-04-06 20:41:47.476643

In [39]:
# Conferência da base:
df_vendedores.tail()

,seller_id,seller_zip_code_prefix,seller_city,seller_state,data_ingestao
3090,98dddbc4601dd4443ca174359b237166,87111,sarandi,PR,2026-04-06 20:41:47.476643
3091,f8201cab383e484733266d1906e2fdfa,88137,palhoca,SC,2026-04-06 20:41:47.476643
3092,74871d19219c7d518d0090283e03c137,4650,sao paulo,SP,2026-04-06 20:41:47.476643
3093,e603cf3fec55f8697c9059638d6c8eb5,96080,pelotas,RS,2026-04-06 20:41:47.476643
3094,9e25199f6ef7e7c347120ff175652c3b,12051,taubate,SP,2026-04-06 20:41:47.476643

In [40]:
# Conferência da tabela:
df_vendedores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   object
 3   seller_state            3095 non-null   object
 4   data_ingestao           3095 non-null   object
dtypes: int64(1), object(4)
memory usage: 121.0+ KB

In [41]:
# Conferência de duplicidade:
print(f'Linhas duplicadas:',df_vendedores.duplicated().sum())

# Conferência de duplicidade na coluna seller_id:
print(f'Duplicidade de seller_id:', df_vendedores['seller_id'].duplicated().sum())

Linhas duplicadas: 0
Duplicidade de seller_id: 0

In [42]:
# Definição de schema:
schema_df_vendedores = {
    'seller_id' : 'string',
     'seller_zip_code_prefix' : 'string',
     'seller_city' : 'string',
     'seller_state' : 'string',
     'data_ingestao' : 'datetime64[ns]'
}

# Ajuste da tipagem de dados do arquivo:
for coluna, tipo_esperado in schema_df_vendedores.items():
    if "datetime" in tipo_esperado:
        df_vendedores[coluna] = pd.to_datetime(df_vendedores[coluna], errors="coerce")
    else:
        df_vendedores[coluna] = df_vendedores[coluna].astype(tipo_esperado)

In [43]:
# Ajustando o nome das cidades para minúsculo:
df_vendedores["seller_city"] = df_vendedores["seller_city"].str.strip().str.lower()
print(f'Quantidade de cidades referente aos vendedores:',df_vendedores["seller_city"].nunique())


# Ajustando as siglas dos estados para maiúsculo:
df_vendedores["seller_state"] = df_vendedores["seller_state"].str.strip().str.upper()
print(f'Quantidade de estados referente aos vendedores:',df_vendedores["seller_state"].nunique())
print(f'ESTADOS -->> ', df_vendedores["seller_state"].unique().tolist())

Quantidade de cidades referente aos vendedores: 611
Quantidade de estados referente aos vendedores: 23
ESTADOS -->>  ['SP', 'RJ', 'PE', 'PR', 'GO', 'SC', 'BA', 'DF', 'RS', 'MG', 'RN', 'MT', 'CE', 'PB', 'AC', 'ES', 'RO', 'PI', 'MS', 'SE', 'MA', 'AM', 'PA']

In [44]:
'''
# TESTAR CONEXÃO DOS JOINS
ids_sellers = set(df_vendedores["seller_id"])
df_invalid = df_itens_pedidos[~df_itens_pedidos["seller_id"].isin(ids_sellers)]
print(df_invalid)
'''

'\n# TESTAR CONEXÃO DOS JOINS\nids_sellers = set(df_vendedores["seller_id"])\ndf_invalid = df_itens_pedidos[~df_itens_pedidos["seller_id"].isin(ids_sellers)]\nprint(df_invalid)\n'

In [45]:
# Salvando arquivo na Silver:
df_vendedores.to_parquet(caminho_silver + 'sellers_silver_dataset.parquet', index=False)

## ORDEM_PAGAMENTO

In [46]:
# Conferência topo:
df_ordem_pagamento.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,data_ingestao
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33,2026-04-06 20:41:47.436454
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39,2026-04-06 20:41:47.436454
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71,2026-04-06 20:41:47.436454
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78,2026-04-06 20:41:47.436454
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45,2026-04-06 20:41:47.436454

In [47]:
# Conferência base:
df_ordem_pagamento.tail()

,order_id,payment_sequential,payment_type,payment_installments,payment_value,data_ingestao
103881,0406037ad97740d563a178ecc7a2075c,1,boleto,1,363.31,2026-04-06 20:41:47.436454
103882,7b905861d7c825891d6347454ea7863f,1,credit_card,2,96.80,2026-04-06 20:41:47.436454
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77,2026-04-06 20:41:47.436454
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54,2026-04-06 20:41:47.436454
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58,2026-04-06 20:41:47.436454

In [48]:
# Conferência geral:
df_ordem_pagamento.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 6 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  object
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
 5   data_ingestao         103886 non-null  object
dtypes: float64(1), int64(2), object(3)
memory usage: 4.8+ MB

In [49]:
# Criação de schema:
schema_ordem_pagamento = {
    'order_id' : 'string',
     'payment_sequential' : 'int',
     'payment_type' : 'string',
     'payment_installments' : 'int',
     'payment_value' : 'float',
     'data_ingestao' : 'datetime64[ns]'
    }


# Ajuste da tipagem de dados do arquivo:
for coluna, tipo_esperado in schema_ordem_pagamento.items():
    if "datetime" in tipo_esperado:
        df_ordem_pagamento[coluna] = pd.to_datetime(df_ordem_pagamento[coluna], errors="coerce")
    else:
        df_ordem_pagamento[coluna] = df_ordem_pagamento[coluna].astype(tipo_esperado)

In [50]:
# Conferência de duplicidade:
print(f'Linhas duplicadas:',df_ordem_pagamento.duplicated().sum())

# Conferência de duplicidade na coluna seller_id:
    # Um pedido pode ter vários pagamentos, por isso do order_id + payment_sequential:
print(f'Duplicidade de order_id + payment_sequential:', df_ordem_pagamento.duplicated(subset=["order_id", "payment_sequential"]).sum())

# Checando a coluna formas de pagamento:
print(f'Formas de pagamento:', df_ordem_pagamento['payment_type'].unique().tolist())

Linhas duplicadas: 0
Duplicidade de order_id + payment_sequential: 0
Formas de pagamento: ['credit_card', 'boleto', 'voucher', 'debit_card', 'not_defined']

In [51]:
# Lista de elementos com valores de pagamento menores que 0 (erro):
df_ordem_pagamento["payment_value"].describe()

count    103886.000000
mean        154.100380
std         217.494064
min           0.000000
25%          56.790000
50%         100.000000
75%         171.837500
max       13664.080000
Name: payment_value, dtype: float64

In [52]:
# Checando a quantidade de parcelas (vendo se não tem nenhum valor errado, negativo por exemplo):
df_ordem_pagamento['payment_installments'].describe()

count    103886.000000
mean          2.853349
std           2.687051
min           0.000000
25%           1.000000
50%           1.000000
75%           4.000000
max          24.000000
Name: payment_installments, dtype: float64

In [53]:
# Checagem do tipo de pagamento:
df_ordem_pagamento["payment_type"].value_counts()

payment_type
credit_card    76795
boleto         19784
voucher         5775
debit_card      1529
not_defined        3
Name: count, dtype: Int64

In [54]:
# Salvando arquivo na Silver:
df_ordem_pagamento.to_parquet(caminho_silver + 'payment_order_silver_dataset.parquet', index=False)

## DF_GEOLOCALIZACAO

In [55]:
# Conferência topo:
df_geolocalizacao.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,data_ingestao
0,1037,-23.545621,-46.639292,sao paulo,SP,2026-04-06 20:41:47.399713
1,1046,-23.546081,-46.644820,sao paulo,SP,2026-04-06 20:41:47.399713
2,1046,-23.546129,-46.642951,sao paulo,SP,2026-04-06 20:41:47.399713
3,1041,-23.544392,-46.639499,sao paulo,SP,2026-04-06 20:41:47.399713
4,1035,-23.541578,-46.641607,sao paulo,SP,2026-04-06 20:41:47.399713

In [56]:
# Conferência base:
df_geolocalizacao.tail()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state,data_ingestao
1000158,99950,-28.068639,-52.010705,tapejara,RS,2026-04-06 20:41:47.399713
1000159,99900,-27.877125,-52.224882,getulio vargas,RS,2026-04-06 20:41:47.399713
1000160,99950,-28.071855,-52.014716,tapejara,RS,2026-04-06 20:41:47.399713
1000161,99980,-28.388932,-51.846871,david canabarro,RS,2026-04-06 20:41:47.399713
1000162,99950,-28.070104,-52.018658,tapejara,RS,2026-04-06 20:41:47.399713

In [57]:
# Conferência geral:
df_geolocalizacao.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 6 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  object
 4   geolocation_state            1000163 non-null  object
 5   data_ingestao                1000163 non-null  object
dtypes: float64(2), int64(1), object(3)
memory usage: 45.8+ MB

In [58]:
schema_df_geolocalizacao = {
    'geolocation_zip_code_prefix' : 'string',
    'geolocation_lat' : 'float',
    'geolocation_lng' : 'float',
    'geolocation_city' : 'string',
    'geolocation_state' : 'string',
    'data_ingestao' : 'datetime64[ns]'
}

# Ajuste da tipagem de dados do arquivo:
for coluna, tipo_esperado in schema_df_geolocalizacao.items():
    if "datetime" in tipo_esperado:
        df_geolocalizacao[coluna] = pd.to_datetime(df_geolocalizacao[coluna], errors="coerce")
    else:
        df_geolocalizacao[coluna] = df_geolocalizacao[coluna].astype(tipo_esperado)

df_geolocalizacao["geolocation_zip_code_prefix"] = df_geolocalizacao["geolocation_zip_code_prefix"].str.zfill(5)
df_geolocalizacao["geolocation_city"] = df_geolocalizacao["geolocation_city"].str.strip().str.lower()
df_geolocalizacao["geolocation_state"] = df_geolocalizacao["geolocation_state"].str.strip().str.upper()

In [59]:
df_geolocalizacao.isnull().sum()

geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
data_ingestao                  0
dtype: int64

In [60]:
df_geolocalizacao_silver = (
    df_geolocalizacao.groupby("geolocation_zip_code_prefix", as_index=False)
    .agg({
        "geolocation_lat": "mean",
        "geolocation_lng": "mean",
        "geolocation_city": "first",
        "geolocation_state": "first",
        "data_ingestao": "first"
    })
)

In [61]:
# Conferindo dados duplicados de prefixo:
df_geolocalizacao_silver.duplicated(subset=["geolocation_zip_code_prefix"]).sum()

np.int64(0)

In [62]:
print(df_geolocalizacao.shape)
print(df_geolocalizacao_silver.shape)

(1000163, 6)
(19015, 6)

In [63]:
# Salvando arquivo na Silver:
df_geolocalizacao_silver.to_parquet(caminho_silver + 'geolocalization_silver_dataset.parquet', index=False)